const STORAGE_KEY='moldLeadManagerV01'; // giữ key cũ để không mất dữ liệu khi nâng V0.2
const seedData={
 leads:[
  {id:'L001',name:'Tanaka Product Lab',company:'Cá nhân / startup',country:'Nhật Bản',need:'Tìm xưởng làm khuôn ép nhựa cho vỏ ABS, lô nhỏ 500–1.000 pcs',source:'X / Web',url:'',score:88,status:'new',note:'Ưu tiên hỏi file 3D, kích thước, số lượng và vật liệu.'},
  {id:'L002',name:'ABC Parts',company:'Doanh nghiệp nhỏ',country:'Nhật Bản',need:'Cần đối tác gia công khuôn dập và chi tiết kim loại số lượng nhỏ',source:'Website',url:'',score:76,status:'contacted',note:'Đã lưu để liên hệ.'}
 ],
 products:[
  {id:'P001',name:'Khuôn ép nhựa vỏ ABS',category:'Khuôn ép nhựa',image:'assets/default.svg',material:'ABS / POM / PP',size:'Khuôn nhỏ & vừa',description:'Thiết kế 3D, gia công khuôn, thử khuôn và hỗ trợ ép sản phẩm.'},
  {id:'P002',name:'Khuôn dập chi tiết kim loại',category:'Khuôn dập',image:'assets/default.svg',material:'Thép / SUS',size:'Theo bản vẽ',description:'Nhận thiết kế và chế tạo khuôn dập theo mẫu hoặc dữ liệu 2D/3D.'}
 ],
 customers:[
  {id:'C001',name:'Tanaka Product Lab',company:'Cá nhân / startup',email:'',phone:'',country:'Nhật Bản',status:'Mới lưu',need:'Vỏ nhựa ABS',note:'Lead từ quét nhu cầu.'}
 ],
 transactions:[
  {id:'T001',date:'2026-09-18',customerId:'C001',project:'Khuôn vỏ ABS',amount:380000,status:'quote',commissionRate:6}
 ],
 settings:{commissionRate:6,workshopName:'Xưởng khuôn của tôi',languages:'Nhật / Việt / Anh',currencyRates:{JPY:1,VND:170,CNY:0.048},pricing:{moldBase:220000,designBase:45000,materialPerKg:650,productionPerPiece:180,setup:25000,moldDays:18,productionDays:5}}
};
let state=loadData(),route='dashboard',selectedProductId=null; const app=document.getElementById('app'),modal=document.getElementById('modal');
function loadData(){try{const d=JSON.parse(localStorage.getItem(STORAGE_KEY))||structuredClone(seedData);d.settings=d.settings||structuredClone(seedData.settings);d.settings.pricing={...seedData.settings.pricing,...(d.settings.pricing||{})};d.settings.currencyRates={...seedData.settings.currencyRates,...(d.settings.currencyRates||{})};d.products=(d.products||[]).map(p=>({...p,images:p.images?.length?p.images:[p.image||'assets/default.svg']}));return d}catch{return structuredClone(seedData)}}
function saveData(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function money(n){return new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(Number(n)||0)}
function toast(m){const e=document.getElementById('toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function setSubtitle(t){document.getElementById('pageSubtitle').textContent=t}
function customer(id){return state.customers.find(x=>x.id===id)}
function render(){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===route));({dashboard:renderDashboard,products:renderProducts,quote:renderQuote,accounts:renderCustomers,customers:renderCustomers,transactions:renderTransactions,settings:renderSettings}[route]||renderDashboard)()}
function renderDashboard(){setSubtitle('Quét FREE nhu cầu về khuôn');const hot=state.leads.filter(x=>x.score>=80).length;app.innerHTML=`<section class="page">
 <div class="hero-mold"><div><small>MOLD LEAD FINDER · FREE SCANNER VN V0.6</small><h2>Tìm khách hàng cần làm khuôn</h2><p>Quét nguồn web công khai miễn phí, không dùng OpenAI API.</p></div><b>${hot} HOT</b></div>
 <div class="stats-grid"><div class="card stat"><div class="value">${state.leads.length}</div><div class="label">Lead đã tìm</div></div><div class="card stat"><div class="value">${hot}</div><div class="label">Lead nóng</div></div><div class="card stat"><div class="value">${state.customers.length}</div><div class="label">Khách đã lưu</div></div><div class="card stat"><div class="value">${state.products.length}</div><div class="label">Sản phẩm xưởng</div></div></div>
 <div class="card scan-card"><h3>🔎 Quét FREE nhu cầu khách hàng</h3><p class="muted">Bản V0.6 thử nghiệm riêng thị trường Việt Nam. Worker tự chuyển giữa nhiều nguồn FREE khi một nguồn bị chặn; không dùng OpenAI, chưa quét Nhật Bản/X.</p><div class="form-grid"><div class="field"><label>Từ khóa</label><input id="scanKeyword" value="khuôn ép nhựa, gia công khuôn, chế tạo khuôn" placeholder="khuôn ép nhựa, khuôn đúc, gia công CNC..."></div><div class="field"><label>Thị trường</label><select id="scanMarket"><option>Việt Nam</option></select></div><div class="field"><label>Nguồn ưu tiên</label><select id="scanSource"><option>Web Việt Nam</option></select></div><button class="primary-btn" type="button" onclick="scanLeads()">🔍 Quét ngay</button><button type="button" onclick="configureFreeWorker()">⚙️ Cài Worker FREE</button></div></div>
 <div class="section-head"><h2>Khách tiềm năng</h2><button class="link-btn" onclick="openLeadForm()">+ Thêm tay</button></div><div class="lead-list">${state.leads.sort((a,b)=>b.score-a.score).map(leadCard).join('')}</div>
 </section>`}
function leadCard(l){return `<div class="card lead-card"><div class="lead-top"><div><span class="source-chip">${esc(l.source)}</span><b>${esc(l.name)}</b><div class="row-sub">${esc(l.company)} · ${esc(l.country)}</div></div><div class="score ${l.score>=80?'hot':''}">${l.score}<small>/100</small></div></div><p>${esc(l.need)}</p><div class="lead-actions"><button onclick="saveLeadAsCustomer('${l.id}')">👤 Lưu khách</button><button onclick="editLead('${l.id}')">✎ Sửa</button>${l.url?`<button onclick="window.open('${esc(l.url)}','_blank')">↗ Nguồn</button>`:''}</div></div>`}
const FREE_WORKER_KEY='moldFreeWorkerUrlV04';
function getFreeWorkerUrl(){return (localStorage.getItem(FREE_WORKER_KEY)||'').trim().replace(/\/$/,'')}
function configureFreeWorker(){
 const current=getFreeWorkerUrl();
 const v=prompt('Dán URL Cloudflare Worker FREE (ví dụ: https://mold-free-scanner.ten-ban.workers.dev)',current);
 if(v===null)return;
 const clean=v.trim().replace(/\/$/,'');
 if(!clean){localStorage.removeItem(FREE_WORKER_KEY);toast('Đã xóa địa chỉ Worker');return}
 if(!/^https:\/\//i.test(clean)){alert('URL Worker phải bắt đầu bằng https://');return}
 localStorage.setItem(FREE_WORKER_KEY,clean);toast('Đã lưu Worker FREE');render();
}
async function scanLeads(){
 const btn=document.querySelector('.scan-card .primary-btn'),raw=document.getElementById('scanKeyword').value.trim()||'khuôn ép nhựa',market='Việt Nam';
 const worker=getFreeWorkerUrl();
 if(!worker){openModal(`<div class="modal-inner"><div class="modal-head"><h3>Chưa cài Worker FREE</h3><button class="icon-btn" onclick="modal.close()">×</button></div><p>Bản V0.6 dùng Cloudflare Worker đa nguồn để quét web Việt Nam miễn phí, không dùng OpenAI.</p><p>Deploy file <b>worker.js</b> trong thư mục <b>cloudflare-worker</b>, sau đó bấm nút bên dưới và dán URL Worker.</p><button class="primary-btn" onclick="modal.close();configureFreeWorker()">⚙️ Nhập URL Worker</button></div>`);return}
 try{
  if(btn){btn.disabled=true;btn.textContent='⏳ Đang quét FREE...'}
  const url=worker+'/scan?keywords='+encodeURIComponent(raw)+'&market='+encodeURIComponent(market);
  const res=await fetch(url,{headers:{'Accept':'application/json'}});
  const text=await res.text(); let data; try{data=JSON.parse(text)}catch{throw new Error('Worker trả dữ liệu không phải JSON: '+text.slice(0,120))}
  if(!res.ok||!data.ok)throw new Error(data.error||('HTTP '+res.status));
  const articles=Array.isArray(data.articles)?data.articles:[];
  const existing=new Set(state.leads.map(x=>x.url).filter(Boolean));
  const fresh=articles.filter(x=>x.url&&!existing.has(x.url)).slice(0,12).map((x,i)=>({id:'L'+(Date.now()+i),name:x.title||'Kết quả web',company:x.domain||'Nguồn web',country:market,need:x.title||raw,source:'FREE · '+(data.source||'Web Việt Nam'),url:x.url,score:Number(x.score)||60,status:'new',note:`Quét FREE thị trường Việt Nam qua Cloudflare Worker đa nguồn, không dùng OpenAI. Từ khóa: ${raw}. Hãy mở Nguồn để xác minh trước khi liên hệ.`}));
  if(!fresh.length){toast('Không thấy kết quả mới. Thử từ khóa khác.');return}
  state.leads=[...fresh,...state.leads];saveData();render();toast(`Tìm thấy ${fresh.length} kết quả FREE`);
 }catch(err){console.error('FREE scan error',err);openModal(`<div class="modal-inner"><div class="modal-head"><h3>Worker FREE chưa quét được</h3><button class="icon-btn" onclick="modal.close()">×</button></div><p>Không gọi OpenAI và không tốn token. Lỗi hiện tại nằm ở Worker hoặc nguồn web.</p><p class="muted">${esc(err.message||err)}</p><div class="lead-actions"><button onclick="modal.close();configureFreeWorker()">⚙️ Kiểm tra URL Worker</button></div></div>`)
 }finally{const b=document.querySelector('.scan-card .primary-btn');if(b){b.disabled=false;b.textContent='🔍 Quét ngay'}}
}
function renderProducts(){setSubtitle('Portfolio sản phẩm của xưởng');app.innerHTML=`<section class="page"><div class="section-head"><div><h2>Sản phẩm / Portfolio</h2><p class="muted">Trưng bày sản phẩm giống catalog bán hàng. Mỗi sản phẩm có thể lưu tối đa 7 ảnh.</p></div><button class="primary-small" onclick="openProductForm()">+ Tạo</button></div><div class="portfolio-grid">${state.products.map(productCard).join('')}</div></section><button class="fab" onclick="openProductForm()">+</button>`}
function productCard(p){const imgs=p.images?.length?p.images:[p.image||'assets/default.svg'];return `<div class="card portfolio-card"><div class="product-gallery" id="gal-${p.id}" data-index="0">${imgs.map((im,i)=>`<img class="gallery-img ${i?'':'active'}" src="${im}" alt="">`).join('')}${imgs.length>1?`<button class="gallery-arrow left" onclick="slideProduct('${p.id}',-1)">‹</button><button class="gallery-arrow right" onclick="slideProduct('${p.id}',1)">›</button><div class="gallery-dots">${imgs.map((_,i)=>`<i class="${i?'':'active'}"></i>`).join('')}</div><span class="photo-count">1/${imgs.length}</span>`:''}</div><div><span class="source-chip">${esc(p.category)}</span><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="row-sub">Vật liệu: ${esc(p.material||'—')} · ${esc(p.size||'')}</div><div class="lead-actions"><button onclick="openProductForm('${p.id}')">✎ Sửa</button><button onclick="deleteProduct('${p.id}')">Xóa</button></div></div></div>`}
function slideProduct(id,dir){const g=document.getElementById('gal-'+id);if(!g)return;const imgs=[...g.querySelectorAll('.gallery-img')],dots=[...g.querySelectorAll('.gallery-dots i')];let i=(Number(g.dataset.index)+dir+imgs.length)%imgs.length;g.dataset.index=i;imgs.forEach((x,n)=>x.classList.toggle('active',n===i));dots.forEach((x,n)=>x.classList.toggle('active',n===i));const c=g.querySelector('.photo-count');if(c)c.textContent=`${i+1}/${imgs.length}`}
function renderQuote(){setSubtitle('Báo giá nhanh đa tiền tệ');app.innerHTML=`<section class="page"><div class="section-head"><div><h2>🧮 Báo giá nhanh</h2><p class="muted">Ước tính sơ bộ theo đơn giá xưởng. Có thể chuyển JPY / VND / CNY ngay trên kết quả.</p></div></div><div class="card quote-card"><div class="currency-switch"><button class="cur-btn active" data-cur="JPY" onclick="setQuoteCurrency('JPY')">¥ JPY</button><button class="cur-btn" data-cur="VND" onclick="setQuoteCurrency('VND')">₫ VND</button><button class="cur-btn" data-cur="CNY" onclick="setQuoteCurrency('CNY')">¥ CNY</button></div><div class="form-grid quote-grid"><div class="field"><label>Loại công việc</label><select id="qType"><option>Khuôn ép nhựa + sản xuất</option><option>Chỉ chế tạo khuôn</option><option>Chỉ sản xuất sản phẩm</option></select></div><div class="field"><label>Vật liệu</label><select id="qMaterial"><option value="1">ABS</option><option value="0.9">PP</option><option value="1.15">POM</option><option value="1.25">PC</option><option value="1.4">Khác / kỹ thuật</option></select></div><div class="dimension-row"><div class="field"><label>Dài (mm)</label><input id="qL" type="number" value="300"></div><div class="field"><label>Rộng (mm)</label><input id="qW" type="number" value="300"></div><div class="field"><label>Cao (mm)</label><input id="qH" type="number" value="50"></div></div><div class="dimension-row"><div class="field"><label>Khối lượng/sp (kg)</label><input id="qKg" type="number" step="0.01" value="1"></div><div class="field"><label>Số lượng</label><input id="qQty" type="number" value="1000"></div><div class="field"><label>Độ phức tạp</label><select id="qComplex"><option value="0.85">Đơn giản</option><option value="1" selected>Trung bình</option><option value="1.35">Phức tạp</option></select></div></div><button class="primary-btn" type="button" onclick="calculateQuote()">Ước tính giá & thời gian</button></div><div id="quoteResult"></div></div></section>`}
let quoteCurrency='JPY',lastQuote=null;
function setQuoteCurrency(cur){quoteCurrency=cur;document.querySelectorAll('.cur-btn').forEach(b=>b.classList.toggle('active',b.dataset.cur===cur));if(lastQuote)showQuoteResult(lastQuote)}
function currencyMoney(jpy,cur=quoteCurrency){const rate=state.settings.currencyRates[cur]||1,n=(Number(jpy)||0)*rate;if(cur==='VND')return new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(n);if(cur==='CNY')return new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',maximumFractionDigits:0}).format(n);return money(n)}
function calculateQuote(){const p=state.settings.pricing,l=Number(qL.value)||0,w=Number(qW.value)||0,h=Number(qH.value)||0,kg=Number(qKg.value)||0,qty=Math.max(1,Number(qQty.value)||1),mat=Number(qMaterial.value)||1,complex=Number(qComplex.value)||1,type=qType.value;const sizeFactor=Math.max(.75,Math.min(2.2,Math.cbrt(Math.max(1,l*w*h)/(300*300*50))));let design=Math.round(p.designBase*complex*sizeFactor),mold=Math.round(p.moldBase*complex*sizeFactor),unit=Math.round((p.productionPerPiece+(kg*p.materialPerKg))*mat*complex),setup=p.setup,total=design+mold+setup+unit*qty,days=Math.ceil(p.moldDays*complex*sizeFactor+p.productionDays*Math.max(1,qty/1000));if(type==='Chỉ chế tạo khuôn'){unit=0;setup=0;total=design+mold;days=Math.ceil(p.moldDays*complex*sizeFactor)}if(type==='Chỉ sản xuất sản phẩm'){design=0;mold=0;total=setup+unit*qty;days=Math.ceil(p.productionDays*Math.max(1,qty/1000))}lastQuote={design,mold,unit,setup,total,days,qty};showQuoteResult(lastQuote)}
function showQuoteResult(q){const eta=new Date();eta.setDate(eta.getDate()+q.days);document.getElementById('quoteResult').innerHTML=`<div class="quote-result"><div class="quote-total"><small>TỔNG ƯỚC TÍNH · ${quoteCurrency}</small><strong>${currencyMoney(q.total)}</strong><span>≈ ${currencyMoney(Math.round(q.total/q.qty))}/sản phẩm (tính cả chi phí ban đầu)</span></div><div class="quote-breakdown"><div><span>Thiết kế</span><b>${currencyMoney(q.design)}</b></div><div><span>Chế tạo khuôn</span><b>${currencyMoney(q.mold)}</b></div><div><span>Setup</span><b>${currencyMoney(q.setup)}</b></div><div><span>Sản xuất ${q.qty.toLocaleString()} sp</span><b>${currencyMoney(q.unit*q.qty)}</b></div></div><div class="delivery-box">⏱ <b>Khoảng ${q.days} ngày</b> · dự kiến hoàn thành ${eta.toLocaleDateString('vi-VN')}</div><p class="small-note">Tỷ giá chuyển đổi dùng giá trị bạn đặt trong Cài đặt, không phải tỷ giá trực tuyến. Báo giá này là sơ bộ, chưa tính vận chuyển, thuế, dung sai đặc biệt, cavity và yêu cầu bề mặt.</p><div class="lead-actions"><button onclick="openQuoteForCustomer(${q.total},${q.days})">👤 Lưu báo giá cho khách</button></div></div>`}
function openQuoteForCustomer(total,days){if(!state.customers.length){toast('Hãy lưu khách hàng trước');return}openModal(`<form class="modal-inner form-grid" onsubmit="saveQuickQuote(event)"><div class="modal-head"><h3>Lưu báo giá</h3><button type="button" class="icon-btn" onclick="modal.close()">×</button></div><div class="field"><label>Khách hàng</label><select name="customerId">${state.customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Dự án</label><input name="project" value="Báo giá sản phẩm / khuôn"></div><div class="field"><label>Giá ước tính (¥)</label><input name="amount" type="number" value="${total}"></div><input type="hidden" name="days" value="${days}"><button class="primary-btn">Lưu vào khách hàng & giao dịch</button></form>`)}
function saveQuickQuote(e){e.preventDefault();const f=new FormData(e.target),cid=f.get('customerId'),c=customer(cid);state.transactions.unshift({id:'T'+Date.now(),date:new Date().toISOString().slice(0,10),customerId:cid,project:f.get('project'),amount:Number(f.get('amount')),status:'quote',commissionRate:state.settings.commissionRate});if(c){c.status='Đã báo giá';c.note=(c.note?c.note+'\n':'')+`Báo giá ${money(Number(f.get('amount')))} · dự kiến ${f.get('days')} ngày · ${new Date().toLocaleDateString('vi-VN')}`}saveData();modal.close();toast('Đã lưu báo giá cho khách')}
function renderCustomers(){setSubtitle('Danh bạ & trạng thái khách hàng');const groups=['Mới lưu','Đã liên hệ','Đang tham khảo giá','Đã báo giá','Đang thương lượng','Đã giao dịch','Không thành công'];app.innerHTML=`<section class="page"><div class="section-head"><div><h2>Khách hàng đã lưu</h2><p class="muted">Không quét ở đây. Chỉ giữ thông tin để liên hệ và theo dõi tiến độ.</p></div><button class="primary-small" onclick="openCustomerForm()">+ Thêm</button></div><div class="customer-summary">${groups.slice(0,6).map(g=>`<div><b>${state.customers.filter(c=>c.status===g||(g==='Mới lưu'&&c.status==='Tiềm năng')).length}</b><span>${g}</span></div>`).join('')}</div><div class="card list">${state.customers.map(c=>`<div class="customer-row"><div class="list-row clickable" onclick="openCustomerForm('${c.id}')"><div class="avatar">${esc(c.name).slice(0,1).toUpperCase()}</div><div><div class="row-title">${esc(c.name)}</div><div class="row-sub">${esc(c.company||'—')} · ${esc(c.need||'Chưa ghi nhu cầu')}</div><div class="contact-line">${esc(c.phone||'')}${c.phone&&c.email?' · ':''}${esc(c.email||'')}</div></div><span class="badge purple">${esc(c.status)}</span></div><div class="customer-actions"><button onclick="openCustomerForm('${c.id}')">✎ Thông tin</button><button onclick="go('quote')">💰 Báo giá</button>${c.phone?`<button onclick="location.href='tel:${esc(c.phone)}'">☎ Gọi</button>`:''}${c.email?`<button onclick="location.href='mailto:${esc(c.email)}'">✉ Email</button>`:''}</div></div>`).join('')||'<div class="empty">Chưa có khách hàng. Hãy lưu lead từ Tổng quan.</div>'}</div></section><button class="fab" onclick="openCustomerForm()">+</button>`}
function renderTransactions(){setSubtitle('Đơn hàng & hoa hồng');const closed=state.transactions.filter(t=>t.status==='closed'),revenue=closed.reduce((s,t)=>s+t.amount,0),fee=closed.reduce((s,t)=>s+t.amount*t.commissionRate/100,0);app.innerHTML=`<section class="page"><div class="commission-hero"><small>Hoa hồng đã chốt</small><strong>${money(fee)}</strong><span>Doanh số chốt: ${money(revenue)}</span></div><div class="stats-grid three"><div class="card stat"><div class="value">${state.transactions.length}</div><div class="label">Giao dịch</div></div><div class="card stat"><div class="value">${closed.length}</div><div class="label">Đã chốt</div></div><div class="card stat"><div class="value">${state.settings.commissionRate}%</div><div class="label">Mặc định</div></div></div><div class="section-head"><h2>Đơn hàng</h2><button class="primary-small" onclick="openTransactionForm()">+ Thêm</button></div><div class="card list">${state.transactions.map(t=>`<div class="list-row clickable" onclick="openTransactionForm('${t.id}')"><div><div class="row-title">${esc(t.project)}</div><div class="row-sub">${esc(customer(t.customerId)?.name||'Khách')} · ${t.date}</div></div><div class="right"><b>${money(t.amount)}</b><div class="row-sub">HH ${t.commissionRate}% = ${money(t.amount*t.commissionRate/100)}</div><span class="badge ${t.status==='closed'?'green':'orange'}">${t.status==='closed'?'Đã chốt':'Đang báo giá'}</span></div></div>`).join('')}</div></section><button class="fab" onclick="openTransactionForm()">+</button>`}
function renderSettings(){setSubtitle('Thiết lập ứng dụng');app.innerHTML=`<section class="page"><h2>Cài đặt</h2><div class="card settings-card"><div class="field"><label>Tên xưởng / thương hiệu</label><input value="${esc(state.settings.workshopName)}" onchange="state.settings.workshopName=this.value;saveData()"></div><div class="field"><label>Hoa hồng mặc định (%)</label><input type="number" min="0" max="100" value="${state.settings.commissionRate}" onchange="state.settings.commissionRate=Number(this.value);saveData()"></div><div class="field"><label>Ngôn ngữ thị trường</label><input value="${esc(state.settings.languages)}" onchange="state.settings.languages=this.value;saveData()"></div><div class="pricing-settings"><h3>Tỷ giá quy đổi từ JPY</h3><p class="small-note">Nhập tỷ giá bạn muốn dùng. Ví dụ 1 JPY bằng bao nhiêu VND/CNY.</p><div class="field"><label>1 JPY = VND</label><input type="number" step="0.01" value="${state.settings.currencyRates.VND}" onchange="state.settings.currencyRates.VND=Number(this.value);saveData()"></div><div class="field"><label>1 JPY = CNY</label><input type="number" step="0.001" value="${state.settings.currencyRates.CNY}" onchange="state.settings.currencyRates.CNY=Number(this.value);saveData()"></div></div><div class="pricing-settings"><h3>Đơn giá dùng cho báo giá nhanh</h3><p class="small-note">Hãy thay bằng số liệu thật của xưởng khi có.</p><div class="field"><label>Thiết kế cơ bản (¥)</label><input type="number" value="${state.settings.pricing.designBase}" onchange="state.settings.pricing.designBase=Number(this.value);saveData()"></div><div class="field"><label>Chế tạo khuôn cơ bản (¥)</label><input type="number" value="${state.settings.pricing.moldBase}" onchange="state.settings.pricing.moldBase=Number(this.value);saveData()"></div><div class="field"><label>Nguyên liệu / kg (¥)</label><input type="number" value="${state.settings.pricing.materialPerKg}" onchange="state.settings.pricing.materialPerKg=Number(this.value);saveData()"></div><div class="field"><label>Gia công / sản phẩm cơ bản (¥)</label><input type="number" value="${state.settings.pricing.productionPerPiece}" onchange="state.settings.pricing.productionPerPiece=Number(this.value);saveData()"></div><div class="field"><label>Setup sản xuất (¥)</label><input type="number" value="${state.settings.pricing.setup}" onchange="state.settings.pricing.setup=Number(this.value);saveData()"></div></div><button class="secondary-btn" onclick="exportData()">Xuất dữ liệu JSON</button><button class="danger-btn" onclick="resetData()">Khôi phục dữ liệu demo</button></div></section>`}
function openLeadForm(id){const l=state.leads.find(x=>x.id===id);openModal(`<form class="modal-inner form-grid" onsubmit="saveLead(event)"><div class="modal-head"><h3>${l?'Sửa':'Thêm'} lead</h3><button type="button" class="icon-btn" onclick="modal.close()">×</button></div><input type="hidden" name="id" value="${l?.id||''}"><div class="field"><label>Tên / đầu mối</label><input name="name" required value="${esc(l?.name||'')}"></div><div class="field"><label>Công ty / loại khách</label><input name="company" value="${esc(l?.company||'')}"></div><div class="field"><label>Quốc gia</label><input name="country" value="${esc(l?.country||'Nhật Bản')}"></div><div class="field"><label>Nhu cầu</label><textarea name="need" required>${esc(l?.need||'')}</textarea></div><div class="field"><label>Nguồn</label><input name="source" value="${esc(l?.source||'Web')}"></div><div class="field"><label>Link nguồn</label><input name="url" type="url" value="${esc(l?.url||'')}"></div><div class="field"><label>Điểm phù hợp</label><input name="score" type="number" min="0" max="100" value="${l?.score||70}"></div><button class="primary-btn">Lưu lead</button></form>`)}
function saveLead(e){e.preventDefault();const f=new FormData(e.target),id=f.get('id')||'L'+Date.now(),x={id,name:f.get('name'),company:f.get('company'),country:f.get('country'),need:f.get('need'),source:f.get('source'),url:f.get('url'),score:Number(f.get('score')),status:'new',note:''};const i=state.leads.findIndex(a=>a.id===id);i>=0?state.leads[i]=x:state.leads.unshift(x);saveData();modal.close();render();toast('Đã lưu lead')}
function editLead(id){openLeadForm(id)}
function saveLeadAsCustomer(id){const l=state.leads.find(x=>x.id===id);if(!l)return;const exists=state.customers.find(c=>c.name===l.name);if(exists){toast('Khách này đã được lưu');return}state.customers.unshift({id:'C'+Date.now(),name:l.name,company:l.company,email:'',phone:'',country:l.country,status:'Mới lưu',need:l.need,note:`Nguồn: ${l.source}`});saveData();toast('Đã lưu vào Khách hàng')}
function openProductForm(id){const p=state.products.find(x=>x.id===id),count=p?.images?.length||1;openModal(`<form class="modal-inner form-grid" onsubmit="saveProduct(event)"><div class="modal-head"><h3>${p?'Sửa':'Thêm'} sản phẩm</h3><button type="button" class="icon-btn" onclick="modal.close()">×</button></div><input type="hidden" name="id" value="${p?.id||''}"><div class="field"><label>Tên sản phẩm / khuôn</label><input name="name" required value="${esc(p?.name||'')}"></div><div class="field"><label>Loại</label><select name="category">${['Khuôn ép nhựa','Khuôn đúc','Khuôn dập','Jig / Fixture','Gia công CNC','Khác'].map(x=>`<option ${p?.category===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Ảnh sản phẩm (tối đa 7 ảnh)</label><input name="imageFiles" type="file" accept="image/*" multiple><small>${p?`Hiện có ${count} ảnh. Chọn ảnh mới sẽ thay bộ ảnh hiện tại.`:'Có thể chọn cùng lúc 5–7 ảnh từ điện thoại/máy tính.'}</small></div><div class="field"><label>Vật liệu</label><input name="material" value="${esc(p?.material||'')}"></div><div class="field"><label>Kích thước / năng lực</label><input name="size" value="${esc(p?.size||'')}"></div><div class="field"><label>Mô tả</label><textarea name="description">${esc(p?.description||'')}</textarea></div><button class="primary-btn">Lưu sản phẩm</button></form>`)}
function saveProduct(e){e.preventDefault();const f=new FormData(e.target),id=f.get('id')||'P'+Date.now(),old=state.products.find(x=>x.id===id),files=[...e.target.elements.imageFiles.files].slice(0,7);const commit=images=>{images=images?.length?images:(old?.images?.length?old.images:[old?.image||'assets/default.svg']);const x={id,name:f.get('name'),category:f.get('category'),image:images[0],images,material:f.get('material'),size:f.get('size'),description:f.get('description')};const i=state.products.findIndex(a=>a.id===id);i>=0?state.products[i]=x:state.products.unshift(x);saveData();modal.close();render();toast('Đã lưu sản phẩm')};if(files.length){Promise.all(files.map(file=>new Promise(res=>{const r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(file)}))).then(commit)}else commit()}
function deleteProduct(id){if(confirm('Xóa sản phẩm này?')){state.products=state.products.filter(x=>x.id!==id);saveData();render()}}
function openCustomerForm(id){const c=state.customers.find(x=>x.id===id);openModal(`<form class="modal-inner form-grid" onsubmit="saveCustomer(event)"><div class="modal-head"><h3>${c?'Sửa':'Thêm'} khách hàng</h3><button type="button" class="icon-btn" onclick="modal.close()">×</button></div><input type="hidden" name="id" value="${c?.id||''}"><div class="field"><label>Tên</label><input name="name" required value="${esc(c?.name||'')}"></div><div class="field"><label>Công ty</label><input name="company" value="${esc(c?.company||'')}"></div><div class="field"><label>Email</label><input name="email" type="email" value="${esc(c?.email||'')}"></div><div class="field"><label>Điện thoại</label><input name="phone" value="${esc(c?.phone||'')}"></div><div class="field"><label>Quốc gia</label><input name="country" value="${esc(c?.country||'Nhật Bản')}"></div><div class="field"><label>Trạng thái</label><select name="status">${['Mới lưu','Đã liên hệ','Đang tham khảo giá','Đã báo giá','Đang thương lượng','Đã giao dịch','Không thành công'].map(x=>`<option ${c?.status===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Nhu cầu</label><textarea name="need">${esc(c?.need||'')}</textarea></div><div class="field"><label>Ghi chú</label><textarea name="note">${esc(c?.note||'')}</textarea></div><button class="primary-btn">Lưu khách hàng</button></form>`)}
function saveCustomer(e){e.preventDefault();const f=new FormData(e.target),id=f.get('id')||'C'+Date.now(),x={id,name:f.get('name'),company:f.get('company'),email:f.get('email'),phone:f.get('phone'),country:f.get('country'),status:f.get('status'),need:f.get('need'),note:f.get('note')};const i=state.customers.findIndex(a=>a.id===id);i>=0?state.customers[i]=x:state.customers.unshift(x);saveData();modal.close();render();toast('Đã lưu khách hàng')}
function openTransactionForm(id){const t=state.transactions.find(x=>x.id===id);openModal(`<form class="modal-inner form-grid" onsubmit="saveTransaction(event)"><div class="modal-head"><h3>${t?'Sửa':'Thêm'} giao dịch</h3><button type="button" class="icon-btn" onclick="modal.close()">×</button></div><input type="hidden" name="id" value="${t?.id||''}"><div class="field"><label>Ngày</label><input type="date" name="date" value="${t?.date||new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Khách hàng</label><select name="customerId">${state.customers.map(c=>`<option value="${c.id}" ${t?.customerId===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Dự án</label><input name="project" required value="${esc(t?.project||'')}"></div><div class="field"><label>Giá trị đơn hàng (¥)</label><input type="number" name="amount" value="${t?.amount||''}"></div><div class="field"><label>Hoa hồng (%)</label><input type="number" step="0.1" name="commissionRate" value="${t?.commissionRate??state.settings.commissionRate}"></div><div class="field"><label>Trạng thái</label><select name="status"><option value="quote" ${t?.status!=='closed'?'selected':''}>Đang báo giá</option><option value="closed" ${t?.status==='closed'?'selected':''}>Đã chốt</option></select></div><button class="primary-btn">Lưu giao dịch</button></form>`)}
function saveTransaction(e){e.preventDefault();const f=new FormData(e.target),id=f.get('id')||'T'+Date.now(),x={id,date:f.get('date'),customerId:f.get('customerId'),project:f.get('project'),amount:Number(f.get('amount')),commissionRate:Number(f.get('commissionRate')),status:f.get('status')};const i=state.transactions.findIndex(a=>a.id===id);i>=0?state.transactions[i]=x:state.transactions.unshift(x);saveData();modal.close();render();toast('Đã lưu giao dịch')}
function openModal(html){document.getElementById('modalContent').innerHTML=html;modal.showModal()}
function go(r){route=r;render();window.scrollTo({top:0,behavior:'smooth'})}
function exportData(){const b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='mold-lead-manager-backup.json';a.click();URL.revokeObjectURL(a.href)}
function resetData(){if(confirm('Khôi phục dữ liệu demo?')){state=structuredClone(seedData);saveData();render()}}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>go(b.dataset.route)));document.getElementById('menuBtn').addEventListener('click',()=>toast('Dùng thanh menu phía dưới để điều hướng'));modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));function startChusenApp(){render()}window.startChusenApp=startChusenApp;Object.assign(window,{go,scanLeads,configureFreeWorker,openLeadForm,saveLead,editLead,saveLeadAsCustomer,openProductForm,saveProduct,deleteProduct,slideProduct,calculateQuote,setQuoteCurrency,openQuoteForCustomer,saveQuickQuote,openCustomerForm,saveCustomer,openTransactionForm,saveTransaction,exportData,resetData});
